# Introduction

Multiple sclerosis (MS) is an automimmune disease affecting the central nervous
system, where the host immune system attacks the myelin sheath of neurons,
resulting in various impairments of visual, sensory, motor, neurocognitive and
autonomic functions. Today, it affects $\approx$ 1M patients in the US alone
[@ramesh]. The most common form of MS is the relapsing-remitting MS (*RRMS*)
which is characterised by active phases of the disease (relapse; *REL*) and
inactive phases (remission; *REM*) [@jelcic].

There is a broad consensus that MS is due to a dysregulated adaptive immunity,
since a number of mutations (>100) in genetic loci involved in adaptive immunity
are linked to MS. One important genetic loci associated with MS is the
*HLA-DR15* serotype of the *HLA-DR* gene, which has been shown to have a strong
association with MS. Since HLA-DR proteins are located on the surface of antigen
presenting cells drive the activation of T-cells, they restrict the space of
possible T cells activated, a strong argument for the involvement of HLA-DR15 in
MS and the broader role of adaptive immunity in MS can be made [@jelcic].

During the relapsing and immunologically active phases of MS, several cells are
known to be important, including CD4+ T-Cells, CD8+ T-cells, as well as
autoantibody-producing B-cells. A phenomenon called autoproliferation (*AP*) of
T cells and B cells plays an important role in MS, since it leads to an
expansion of these self-reacting immune cells. Autoproliferation is mediated by memory
B-cells, as B cells are known to present autoantigen to T cells (via, for
instance, HLA-DR15). This mechanism is further corroborated by the fact that the
depletion of B-cells leads to reduced T cell autoproliferation, and is one of
the principles behind B cell-depleting therapies [@dendrou2015immunopathology].
Previous studies have found that the frequency of AP cells was different between
stages of RRMS, being higher in REL than in REM [@jelcic]. This underpins the
importance of our choice to focus on B cells in this project.

B cells are lymphocytes and part of the adaptive immune response. At its surface
is the B-cell receptor (BCR) that can bind to antigens. The antigen-binding part
of the BCR is a membrane-bound immunoglobulin which can take on one of several
classes known as *isotypes*. The most important isotypes are IgM, IgD, IgG, IgA
and IgE. Upon binding, the B-cell will differentiate into plasmocytes --a type
of effector cell-- that later on produce immunoglobulins (Ig). The secreted Ig
are of the same isotype as the BCR and bind their target antigens [@janeway].

The general process of adaptive immunity is driven by the clonal selection
theory. This theory states that there are many different B cells in the body,
each capable of producing antigen-specific antibodies and corresponding
antigen-specific BCRs. In this pool of many different B cells, those that bind
an antigen upon infection are activated and subsequently divide to produce many
identical copies of themselves--a phenomenon referred to as clonal expansion--
thereby producing clonotypes, which are populations of very similar, clonally
expanded cells. [@janeway].

In order to make inferences about the size of each clonotype, it is important to
reconstruct the sequence of the BCR from single cell RNA sequencing data
(scRNA-seq). This will allow for the usage of the entire transcriptomic identity
of the B-cell without the need to use special targeted sequencing protocols like
repertoire sequencing (Rep-Seq). The tool employed in this project that can
achieve BCR reconstruction from scRNA-Seq data is `BraCeR`, an extension of the
previously developed `TraCeR` for TCR reconstruction [@lindeman] [@stubbington].

In the context of this project, we were provided with scRNA-Seq data for B cells
from 31 patients. The status of each of the patients --*RRMS NAT* - treated with
<<<<<<< HEAD
the monoclonal antibody Natalizumab, *RRMS nihil* - untreated and
*Healthy Donors*--donated lymphocytes, which were then incubated in vitro and
colored with the CFSE dye, a validated method to measure lymphocyte
proliferation and survival [@hawkins2007measuring].
The status of each of the incubated samples was then recorded, and either
corresponded to autoproliferating (*AP*), containing low
concentrations of CFSE (*CFSEdim*), or non autoproliferating (*nonAP*),
containing high concentrations of CFSE(*CFSEhi*). The reduction in dye concentration is attributed to the successive halving of CFSE molecule concentration upon each
division cycle.
=======
the monoclonal antibody Natalizumab, *RRMS nihil* - untreated and *Healthy
Donors*--donated lymphocytes, which were then incubated in vitro and colored
with the CFSE dye, a validated method to measure lymphocyte proliferation and
survival [@hawkins2007measuring]. The status of each of the incubated samples
was then recorded, and either corresponded to autoproliferating (*AP*),
containing low concentrations of CFSE (*CFSEdim*), or non autoproliferating
(*nonAP*), containing high concentrations of *CFSE*. The reduction in dye
concentration is attributed to the successive halving of CFSE molecule
concentration upon each division cycle.
>>>>>>> a70a72b... :pencil: additional intro edits

This report is structured as follows: first, we perform an exploratory data
analysis on the data where we lay out the experimental setting; second, we
exposit our preprocessing pipeline using BraCer; third, we analyze clonotype
frequency in *AP* and *nonAP*; fourth we perform an analysis of the isotype
frequencies in *AP* and *nonAP*.

Our null hypothesis is, that there is no difference between the two conditions
*AP* and *nonAP* in terms of clonal expansion.