# Discussion

We started off with a dataset of B cells of 31 relapsing-remitting mutliple 
sclerosis (RRMS) patiens that were either treated with the antibody natalizumab 
or without as well as healthy donors. These were categorised according to two 
types of conditions (CFSEdim/high) which correspond to autoproliferating (AP)
and non-autoproliferating (nonAP). 

First, we did an exploratory data analysis and found that the dataset
was well balanced in terms of diagnosis (RRMS NAT; RRMS nihil and Healthy 
Donors). As well the number of patients per condition
(AP vs. nonAP) was similar. This pointed to a good balance on the
patient-level.

In a next step we assessed the descriptive statistics of the cell-level and saw
that the 
dataset was even $\sim$ normally distributed in terms of cell counts.

With this dataset we aimed to reconstruct the BCR and ran the
`assemble` step of the BCR via the pipeline `BraCeR` and subsequently `summarise`.
This pipeline gave us the necessary information to answer our first question,
whether there is a difference in clonal expansion between AP cells and nonAP. 

In a first step we analysed the absolute proportion of clonally expanded cells 
in our dataset and we saw that AP cells were in fact more expanded and that AP 
cells had as well a larger share of highly expanded clones than nonAP cells 
($\geq$ 4). When looking at the same plot but now as relative frequencies and 
split up by Diagnosis we did not observe a clear trend apart from AP cells being
more clonally expanded than nonAP. This means that at this stage there was no
difference between RRMS NAT, RRMS nihil and Healthy donors in terms of
relative frequencies.

When plotting now the proportion of clonally expanded cells (a cell is clonally
expanded if it is in a cluster with $\geq 2$ total cells) we saw that indeed AP
cells were more expanded
than nonAP cells. This is as well supported by a Wilcoxon test for nonparametric
data. This supports our hypothesis, that AP sample cells are more highly 
clonally expanded than nonAP cells. When looking at the difference again between diagnosis, we did not inspect any difference visually.

In a next step in the context of clonal expansion analysis we wanted to assess
whether the known variant HLA-DR15 (see introduction) had an influence
on the clonal expansion of B cells. Again via visual inspection we could deduce
there is no difference between HLA-DR15 positive and negative samples in terms
of AP and nonAP cells.

In a very last step we visualized the isotype proportions between the AP and 
nonAP samples. We saw that there were significant differences between AP and 
nonAP isotypes IGHD, IGHDM, IGHG2, IGHM and a difference in the 
isotypes that could not be assigned. 