# Summary

In this project, we have preprocessed scRNA-seq data from B cells sampled from a
population of healthy donors and patients affected by RRMS. A fraction of these
patients were administered with Natalizumab, a therapeutic drug for RRMS aiming
to lower autoreactive T cell intrusion in the CNS. These samples were then
further incubated and annotated as AP vs. nonAP according to the staining with
the dye CFSE. The dye is more dim among expanding cell populations, while being
retained in high intracellular concentrations when cells do not divide. First,
as expected, we saw increased and statistically significant expansion of B cell
clonotypes among samples labeled as AP. Second, the diagnosis status of the
patients from which the samples were drawn did not result in differences in
clonal expansion. Third, we saw that Natalizumab did not have an effect on B
cell clonotype expansion. Fourth, we saw that there was a higher amount of
clonotypes distributed among the AP samples than the nonAP samples. Fifth, we
saw no change in B cell clonotype expansion depending on whether or not the
patient from which the cells were sampled contained the HLA-DR15 variant, which
primarily affects T cells and is hypothesized to be involved in the aetiology of
RRMS. Lastly, we observed some differences in isotype proportions among AP and
nonAP samples.

# References