# Introduction

Multiple sclerosis (MS) is an automimmune disease affecting the central nervous
system. It attacks the myelin sheet of neurons and affects $\approx$ 1M patients
in the US alone. [@ramesh] Patients often experience impairments of visual,
sensory, motor, neurocognitive and autonomic functions. The most common form of
MS is the relapsing-remitting MS (RRMS) which is characterised by active phases
of the disease (relapse; REL) and inactive phases (remission; REM) [@jelcic].

There is a broad consensus that MS is due to a dysregulated adaptive immunity.
During the relapsing phases of MS, several cells are known to be important, such
as CD4+ T-Cells, CD8+ T-cells as well as autoantibody-producing B-cells. A
phenomenon called autoproliferation (AP) of T cells and B cells plays an
important role in MS, since it produdes self-reacting immune cells.
Autoproliferation is mediated by memory B-cells, since B cells are known to
present autoantigen to T cells and it has been shown that the depletion of
B-cells leads to reduced T cell autoproliferation. Autoantigen presentation to T
cells by B cells is as well one of the principles behind B cell-depleting
therapies, underlining the importance of pro-inflammatory B-cells. Previous
studies have found that the frequency of AP cells was different between stages
of RRMS, being higher in REL than in REM [@jelcic]. In this project we focused
on the analysis of B cells.

B cells are lymphocytes and part of the adaptive immune response. At its surface
is the B-cell receptor (BCR) that can bind to antigens. Upon binding the B-cell
will differentiate into plasmocytes --a type of effector cell-- that later on
produce immunoglobulins (Ig) and those will target the object whose antigen
bound to the BCR [@janeway].

The general process of adaptive immunity is underpinned by clonal selection
theory. This theory states that there are many different B cells in the body,
each capable of producing specific antibodies and corresponding specific BCRs.
In this pool of many different B cells, those that bind an antigen upon
infection are activated and subsequently divide to produce many identical copies
of themselves --a phenomenon referred to as clonal expansion-- thereby producing
clonotypes, which are populations of similar, clonally expanded cells.
[@janeway].

In order to make inferences about the size of each clonotype, it is important to
reconstruct the sequence of the BCR from single cell RNA sequencing data
(scRNA-seq). This will allow for the usage of the entire transcriptomic identity
of the B-cell without the need to use special targeted sequencing protocols like
repertoire sequencing (Rep-Seq). The tool employed in this project that can
achieve BCR reconstruction from scRNA seq data is BraCeR, an extension of the
previously developed TraCeR for TCR reconstruction [@lindeman] [@stubbington].

In the context of this project the were provided with B-cell sequencing data
from 31 patients which were categorised as being either autoproliferating (AP)
or non-autoproliferating (nonAP). The disease status (RRMS NAT - treated with
the monoclonal antibody Natalizumab, RRMS nihil - untreated and Healthy Donors)
was recorded for each.

This report is structured as follows: first, we perform an exploratory data
analysis on the data where we lay out the experimental setting; second, we
expound our preprocessing pipeline using BraCer; third, we perform an analysis
of clonotype frequency in AP and nonAP.
