# Isotype Analysis 

```{r Isotype analysis, message = FALSE}

#load annotations
load("annotation.RData")

# cut the lib id string and keep only the first part
separate(data = simplified_annotation, col = lib_id, into = c("lib_id", "rest"), extra = "merge") %>% select(-rest) -> simplified_annotation

# Load data, note that summarise_data should be in data/
file_path = paste0(Sys.getenv(c("HOME_DIR")),"data/summarise_data")

# prepare empty df
isotype_df = data.frame()

# loop over all files and fill the dataframes
for (i in list.files(path = file_path)){
  tmp_path = paste0(file_path,"/",i,"/BCR_summary.txt")

  # read the file line by line
  l = readLines(tmp_path)

  # find the start about the section about the isotypes
  start_line = grep("##Isotype of cells with productive heavy chain##",l)+2

  # find empty lines in file
  empty_lines = which(!nzchar(l))

  # find first empty line after starting line
  end_line = empty_lines[empty_lines > start_line][1]-1

  tmp_table = read.table(tmp_path, skip = start_line, nrows =
                          (end_line-start_line), header = FALSE) %>%
    as.data.frame()

  colnames(tmp_table) = c("Isotype", "cells", "% of cells")

  #split the string at "-" or "_" to remove "-preprocessed" and "POOL*"
  # and remove the "B"
  lib_name = strsplit(i, "[-_]+") %>% unlist() %>% .[1]
  lib_name = sub("B","",lib_name)

  tmp_table$lib_id = lib_name

  isotype_df = rbind(isotype_df, tmp_table)
}

# merge the annotation with the data frames
isotype_df = merge(isotype_df, simplified_annotation, by.x = "lib_id", by.y = "lib_id")
```

```{r, message=FALSE, warning=FALSE}
library(ggplot2)
library(ggpubr)
library(rstatix)
library(stringr)

#unmapped isotypes = unmapped
unmapped <- sum(str_count(isotype_df$Isotype, "Unknown"))
df <- isotype_df[isotype_df$Isotype=="Unknown",]

p <- ggplot(isotype_df, aes(x = Isotype, y = `% of cells`, color = Sample.Type, fill = Sample.Type)) +
  geom_boxplot()+ ylim(0,100) + xlab("Isotype") + ylab("proportion (%)")+
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  stat_compare_means(method = "wilcox", aes(label = ..p.adj..), label = "p.signif",
         symnum.args = list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1),
         symbols = c("****", "***", "**", "*", "ns")))
p
```